# Generated by Django 4.2.4 on 2023-09-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('mother', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('state_of_marrieg', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('state_of_mariege', models.CharField(blank=True, max_length=255, null=True)),
                ('the_job', models.CharField(blank=True, max_length=255, null=True)),
                ('work_where', models.CharField(blank=True, max_length=255, null=True)),
                ('livewhere', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
