# Generated by Django 4.2.4 on 2023-09-11 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core.Account.mother+', to='core.parent'),
        ),
        migrations.AddField(
            model_name='parent',
            name='married_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parent'),
        ),
        migrations.AlterField(
            model_name='account',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core.Account.father+', to='core.parent'),
        ),
    ]
